adapt to changes in mulle-bashfunctions

diff --git a/mulle-semver b/mulle-semver
--- a/mulle-semver
+++ b/mulle-semver
@@ -246,6 +246,12 @@ main()
 ###
 ### INIT
 ###
+_fatal()
+{
+   echo "$0 fatal error: $*" >&2
+   exit 1
+}
+
 _init()
 {
    # leading backslash ? looks like we're getting called from
@@ -264,9 +270,9 @@ _init()
       then
          if [ -z "`command -v 'mulle-bashfunctions-env'`" ]
          then
-            echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH ($PATH) - mulle-bashfunctions not installed ?" >&2
+            _fatal "mulle-bashfunctions-env not installed"
          else
-            echo "Fatal Error: Could not find libexec-dir of mulle-bashfunctions-env (${PWD#${MULLE_USER_PWD}/})" >&2
+            _fatal "Could not find libexec-dir of mulle-bashfunctions-env"
          fi
          exit 1
       fi
@@ -274,8 +280,7 @@ _init()
 
       # shellcheck source=../mulle-bashfunctions/src/mulle-bashfunctions.sh
    . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" ||
-      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
-
+      _fatal "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"
    ### *** ###
    if [ -z "${MULLE_SEMVER_LIBEXEC_DIR}" ]
    then
